baseurl = "https://lluapsa.com"
DefaultContentLanguage = "en-us"
title = "LLU APSA"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true
#disqusShortname = "XXX"
#googleAnalytics = "XXX"
publishDir = "docs"

[Params]
  subtitle = "The Loma Linda University chapter of the American Physician Scientist Association"
  logo = "img/circle-text-dark.svg.png"
  favicon = "img/circle-text-dark.svg.png"
  dateFormat = "January 2, 2006"
  commit = false
  #rss = true
  comments = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"
   PaginatePath = "post"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "LLU APSA"
  email = "lluapsa@gmail.com"
  facebook = "groups/lluapsa"
  #googleplus = "+username" # or xxxxxxxxxxxxxxxxxxxxx
  #github = "username"
  #twitter = "username"
  #reddit = "username"
  #linkedin = "username"
  #xing = "username"
  #stackoverflow = "users/XXXXXXX/username"
  #snapchat = "username"
  #instagram = "username"
  #youtube = "user/username" # or channel/channelname
  #soundcloud = "username"
  #spotify = "username"
  #bandcamp = "username"
  #itchio = "username"

#[[menu.main]]
#    name = "Blog"
#    url = ""
#    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 1

[[menu.main]]
    name = "Community"
    url = "page/community/"
    weight = 2

[[menu.main]]
    name = "Academics"
    url = "page/academics/"
    weight = 3

#[[menu.main]]
#    parent = "samples"
#    name = "Math Sample"
#    url = "post/2017-03-05-math-sample"
#    weight = 2

#[[menu.main]]
#    parent = "samples"
#    name = "Code Sample"
#    url = "post/2016-03-08-code-sample"
#    weight = 3

#[[menu.main]]
#    name = "Tags"
#    url = "tags"
#    weight = 3

